### ISSUE TITLE
 配置文件属性值有"^"这个符号的时候就会出错了

### ISSUE THREAD

**Issue by yfm10** [DevopsJK/SuitAgent#1]
例如数据库密码含^符号，就会出现
java.lang.StringIndexOutOfBoundsException: String index out of range: -5
	at java.lang.String.substring(String.java:1967)
	at com.falcon.suitagent.plugins.plugin.oracle.OraclePlugin.init(OraclePlugin.java:229)
	at com.falcon.suitagent.plugins.util.PluginLibraryHelper.register(PluginLibraryHelper.java:174)
	at com.falcon.suitagent.Agent.work(Agent.java:317)
	at com.falcon.suitagent.Agent.agentServerStart(Agent.java:194)
	at com.falcon.suitagent.Agent.run(Agent.java:69)

**Comment by wanghy8166** [comment]
改密码
